import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import { DataProvider } from "@/dataManager/DataContext";
import { ConfirmDialogProvider, useConfirmDialog } from "@/contexts/ConfirmDialogContext";
import { ConfirmDialog } from "@/components/ConfirmDialog";
import ConfirmDialogRenderer from "@/components/ConfirmDialogRenderer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DataProvider>
          <ConfirmDialogProvider>
            {children}
            <ConfirmDialogRenderer />
            <Toaster position="top-center" duration={1000} />
          </ConfirmDialogProvider>
        </DataProvider>
      </body>
    </html>
  );
}
