name: CI

on:
  push:
    branches:
      - main

jobs:
  notify-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger backend build
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets._GITHUB_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Machigatte/orinote/dispatches \
            -d '{"event_type":"frontend-updated"}'
