name: Build and push Docker image

on:
  repository_dispatch:
    types: [backend-release]

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version from dispatch payload
        id: set_version
        run: |
          echo "VERSION=${{ github.event.client_payload.version || github.event.client_payload.tag || github.event.client_payload.ref || 'latest' }}" >> $GITHUB_ENV

      - name: Print info
        run: |
          echo "Dispatch payload: ${{ toJson(github.event.client_payload) }}"
          echo "Using version: $VERSION"

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/heartmanuscript:${{ env.VERSION }}
            ${{ vars.DOCKERHUB_USERNAME }}/heartmanuscript:latest

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          body: ${{ github.event.client_payload.release_notes || 'Release created by backend release dispatch' }}
          draft: false
          prerelease: ${{ github.event.client_payload.prerelease == true || github.event.client_payload.prerelease == 'true' }}
